<template>
  <div id="cart">
      <navbar class="navbar">
          <div slot="center">购物车</div>
      </navbar>
        <scroll>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
            <li>
                <h1>a</h1>
            </li>
        </scroll>
  </div>
</template>

<script>
import navbar from 'common/navbar/NavBar.vue'
import Scroll from 'common/scroll/Scroll'
export default {
    components:{
        navbar,
        Scroll
    }
}
</script>

<style scoped>
#cart{
      padding-top: 44px;
    height: 100vh;
    position: relative;
}
   #cart .navbar {
        background-color: tomato;
        color: #ffffff;
    }
    .wrappers{
        position: absolute;
        top: 50px;
        left: 0;
        /* height: 0; */
        bottom: 30px;
        /* height: 300px; */
        overflow: hidden;
            /* overflow: hidden;
    position: absolute;
    top: 44px;
    bottom: 49px;
    right: 0;
    left: 0; */
    }
</style>